version: '3.8'

services:
  web:
    image: ghcr.io/rihanodev/web-portofolio-frontend:latest
    container_name: web-portofolio-frontend
    ports:
      - "8080:80"  # Change to 8080:3000 if using Dockerfile.node
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]  # Change to localhost:3000 if using Node.js version
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    labels:
      - "com.docker.compose.project=web-portofolio"
